version: '2'
services:
 play:
  build:
   context: .
   dockerfile: Dockerfile.compose
  image: playwords_c
  command: python playenglish.py
  environment:
   DISPLAY: :0
  volumes:
   - .:/code
   - /tmp/.X11-unix:/tmp/.X11-unix
